import { test } from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  buildMemoryIndex,
  buildPreAction,
  renderDreamLogEntry,
  buildEventJson,
  runRebuildIndexes,
  stageRebuildPlan,
  _internals,
} from '../lib/dream/phase-5-rebuild-indexes.js';

async function tmpDir() {
  return await fs.mkdtemp(path.join(os.tmpdir(), 'dream-p5-'));
}

async function writeFile(p, content) {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, content);
}

const EMPTY_PLANS = {
  routePlan: { reinforce: [], promote: [], declined: [], removeReference: [] },
  prunePlan: {
    corrections: { archive: [] }, sessionIndex: { archive: [] },
    journal: {}, demotions: [],
  },
  datesPlan: { byFile: [], contradictions: [] },
};
const EMPTY_SUMMARIES = {
  phase1Summary: { journalEntriesByBucket: {}, sessionMarkersByKind: {} },
  phase2Summary: { scoredInsightCount: 0, aboveThresholdCount: 0 },
  phase3Summary: {
    correctionsArchivedBlocks: 0, correctionsKeptBlocks: 0,
    sessionIndexArchivedBlocks: 0, sessionIndexKeptBlocks: 0,
    journalArchived: 0, demotedCount: 0,
  },
  phase4Summary: {
    filesWithReplacements: 0, totalReplacements: 0,
    contradictionCount: 0, contradictionsStub: true,
    workingMemoryOverflowSkipped: 0, preStagedHits: 0,
  },
};

test('buildMemoryIndex: emits stable section headers and counts', async () => {
  const dir = await tmpDir();
  await writeFile(path.join(dir, 'working-memory.md'), 'wm\n');
  await writeFile(path.join(dir, 'corrections.md'), 'c\n');
  await fs.mkdir(path.join(dir, 'patterns', 'active'), { recursive: true });
  await writeFile(path.join(dir, 'patterns', 'active', 'foo.md'), 'p\n');
  await fs.mkdir(path.join(dir, 'archive', 'dreams', '2026-05-09'), { recursive: true });

  const out = await buildMemoryIndex({ memoryRoot: dir, today: '2026-05-10' });
  assert.match(out, /^# Memory Index/m);
  assert.match(out, /Generated by \/dream on 2026-05-10/);
  assert.match(out, /## Hot tier/);
  assert.match(out, /## Warm tier/);
  assert.match(out, /## Cold tier/);
  assert.match(out, /✅ `working-memory\.md`/);
  assert.match(out, /⚪ `pre-action\.md`/); // not present yet
  assert.match(out, /patterns\/active\/ — 1 files/);
  assert.match(out, /archive\/dreams\/ — 1 entries/);
});

test('buildPreAction: empty active dir produces a no-patterns notice', async () => {
  const dir = await tmpDir();
  const out = await buildPreAction({ memoryRoot: dir, today: '2026-05-10' });
  assert.match(out, /^# Pre-Action Rules/m);
  assert.match(out, /No active patterns yet/);
});

test('buildPreAction: top-N sorted by importance, then sightings, then alpha', async () => {
  const dir = await tmpDir();
  const adir = path.join(dir, 'patterns', 'active');
  await fs.mkdir(adir, { recursive: true });
  // Make 10 patterns with mixed importance
  const patterns = [
    { name: 'low-importance', importance: 3, sightings: 50 },
    { name: 'top-1', importance: 10, sightings: 1, title: 'Top 1' },
    { name: 'top-2', importance: 9, sightings: 1 },
    { name: 'mid-1', importance: 7, sightings: 5 },
    { name: 'mid-2', importance: 7, sightings: 3 },
    { name: 'mid-3-alpha', importance: 7, sightings: 5 },
    { name: 'mid-3-beta', importance: 7, sightings: 5 },
    { name: 'mid-4', importance: 6, sightings: 1 },
    { name: 'mid-5', importance: 5, sightings: 1 },
    { name: 'mid-6', importance: 4, sightings: 1 },
  ];
  for (const p of patterns) {
    await fs.writeFile(path.join(adir, `${p.name}.md`), `---
title: ${p.title || p.name}
importance: ${p.importance}
sightings: ${p.sightings}
---
body
`);
  }
  const out = await buildPreAction({ memoryRoot: dir, today: '2026-05-10' });
  // top-1 should be at the top of the list
  const lines = out.split('\n').filter(l => l.startsWith('- **'));
  assert.equal(lines.length, _internals.PRE_ACTION_TOP_N);
  assert.match(lines[0], /\*\*top-1\*\*/);
  assert.match(lines[1], /\*\*top-2\*\*/);
  // Tie on importance=7 + sightings=5: alpha order (mid-1 before mid-3-alpha)
  // mid-1 (importance=7, sightings=5) wins over mid-3-alpha (same)? No wait,
  // both have importance=7, sightings=5 → tie-break alpha. mid-1 < mid-3-alpha
  assert.ok(lines.find(l => l.includes('mid-1')));
});

test('buildPreAction: respects action_trigger frontmatter when present', async () => {
  const dir = await tmpDir();
  const adir = path.join(dir, 'patterns', 'active');
  await fs.mkdir(adir, { recursive: true });
  await fs.writeFile(path.join(adir, 'foo.md'), `---
title: Foo Pattern
importance: 8
sightings: 5
action_trigger: BEFORE doing X, do Y
---
body
`);
  const out = await buildPreAction({ memoryRoot: dir, today: '2026-05-10' });
  assert.match(out, /BEFORE doing X, do Y/);
});

test('renderDreamLogEntry: includes verdict, all four phase sections', () => {
  const out = renderDreamLogEntry({
    today: '2026-05-10',
    verdict: 'PASS-TENTATIVE',
    ...EMPTY_SUMMARIES,
    routePlan: EMPTY_PLANS.routePlan,
    prunePlan: EMPTY_PLANS.prunePlan,
    datesPlan: EMPTY_PLANS.datesPlan,
  });
  assert.match(out, /^## 2026-05-10 PASS-TENTATIVE/m);
  assert.match(out, /\*\*Source signal\*\*/);
  assert.match(out, /\*\*Insights \/ route\*\*/);
  assert.match(out, /\*\*Pruned\*\*/);
  assert.match(out, /\*\*Dates \+ contradictions\*\*/);
  assert.match(out, /\*\*Auditor\*\*: pending/);
  assert.match(out, /contradictions: STUB/);
});

test('renderDreamLogEntry: surfaces working-memory overflow warning when present', () => {
  const out = renderDreamLogEntry({
    today: '2026-05-10', verdict: 'PASS-TENTATIVE',
    ...EMPTY_SUMMARIES,
    phase4Summary: {
      ...EMPTY_SUMMARIES.phase4Summary,
      workingMemoryOverflowSkipped: 1,
    },
    routePlan: EMPTY_PLANS.routePlan, prunePlan: EMPTY_PLANS.prunePlan,
    datesPlan: EMPTY_PLANS.datesPlan,
  });
  assert.match(out, /working-memory\.md overflow/);
});

test('renderDreamLogEntry: surfaces journal collision when present', () => {
  const out = renderDreamLogEntry({
    today: '2026-05-10', verdict: 'PASS-TENTATIVE',
    ...EMPTY_SUMMARIES,
    phase3Summary: {
      ...EMPTY_SUMMARIES.phase3Summary,
      journalArchiveCollision: true,
    },
    routePlan: EMPTY_PLANS.routePlan, prunePlan: EMPTY_PLANS.prunePlan,
    datesPlan: EMPTY_PLANS.datesPlan,
  });
  assert.match(out, /COLLISION/);
});

test('buildEventJson: produces well-formed JSON with required schema fields', () => {
  const obj = buildEventJson({
    today: '2026-05-10', verdict: 'PASS-TENTATIVE',
    consumerName: 'test-consumer',
    gitTag: 'dream/pre/2026-05-10',
    ...EMPTY_SUMMARIES,
    routePlan: EMPTY_PLANS.routePlan, prunePlan: EMPTY_PLANS.prunePlan,
    datesPlan: EMPTY_PLANS.datesPlan,
  });
  assert.equal(obj.schema_version, '1.0.0');
  assert.equal(obj.consumer_name, 'test-consumer');
  assert.equal(obj.git_tag, 'dream/pre/2026-05-10');
  assert.equal(obj.verdict, 'PASS-TENTATIVE');
  assert.ok(obj.source_signal);
  assert.ok(obj.routed);
  assert.ok(obj.pruned);
  assert.ok(obj.dates);
  assert.ok(obj.contradictions);
  assert.equal(obj.contradictions.stub, true);
  assert.deepEqual(obj.audit.stage_a, { verdict: 'pending', findings: [] });
});

test('buildEventJson: includes routePlan reinforcements + promotions', () => {
  const obj = buildEventJson({
    today: '2026-05-10', verdict: 'PASS-TENTATIVE',
    ...EMPTY_SUMMARIES,
    routePlan: {
      reinforce: [{ pattern: 'foo', sightingsAfter: 12 }],
      promote: [{ slug: 'new-thing', importance: 9, journalMentions: 4 }],
      declined: [{ slug: 'too-soft', reason: 'weighted_evidence=2.0' }],
      removeReference: [{ slug: 'fresh-promo' }],
    },
    prunePlan: EMPTY_PLANS.prunePlan, datesPlan: EMPTY_PLANS.datesPlan,
  });
  assert.equal(obj.routed.patterns_reinforced.length, 1);
  assert.equal(obj.routed.patterns_reinforced[0].pattern, 'foo');
  assert.equal(obj.routed.patterns_promoted[0].slug, 'new-thing');
  assert.equal(obj.routed.patterns_promotion_declined[0].reason, 'weighted_evidence=2.0');
  assert.equal(obj.routed.reference_removals[0].slug, 'fresh-promo');
});

test('runRebuildIndexes: emits all five artifacts with non-empty content', async () => {
  const dir = await tmpDir();
  const { plan, summary } = await runRebuildIndexes({
    memoryRoot: dir, today: '2026-05-10',
    consumerName: 'test', gitTag: 'dream/pre/2026-05-10',
    ...EMPTY_SUMMARIES,
    ...EMPTY_PLANS,
  });
  assert.ok(plan.memoryIndex.content.length > 0);
  assert.ok(plan.preAction.content.length > 0);
  assert.ok(plan.dreamLogEntry.content.length > 0);
  assert.ok(plan.eventJson.content.length > 0);
  assert.ok(plan.dreamLog.content.length > 0);
  // dreamLog starts with header for new file
  assert.match(plan.dreamLog.content, /^# Dream Log/);
  assert.equal(summary.verdict, 'PASS-TENTATIVE');
});

test('runRebuildIndexes: appends to existing .dream-log.md (preserving prior entries)', async () => {
  const dir = await tmpDir();
  await writeFile(path.join(dir, '.dream-log.md'), '# Dream Log\n\n## 2026-05-09 PASS\n\nprior entry\n');
  const { plan } = await runRebuildIndexes({
    memoryRoot: dir, today: '2026-05-10',
    ...EMPTY_SUMMARIES, ...EMPTY_PLANS,
  });
  assert.match(plan.dreamLog.content, /## 2026-05-09 PASS/);
  assert.match(plan.dreamLog.content, /## 2026-05-10/);
  // Order: prior entry first, new entry after
  const idx9 = plan.dreamLog.content.indexOf('2026-05-09');
  const idx10 = plan.dreamLog.content.indexOf('2026-05-10');
  assert.ok(idx9 < idx10);
});

test('runRebuildIndexes: rejects bad today + missing memoryRoot', async () => {
  await assert.rejects(() => runRebuildIndexes({}), /memoryRoot required/);
  await assert.rejects(
    () => runRebuildIndexes({ memoryRoot: '/x' }),
    /today required/,
  );
  await assert.rejects(
    () => runRebuildIndexes({ memoryRoot: '/x', today: 'foo' }),
    /YYYY-MM-DD/,
  );
});

test('stageRebuildPlan: writes 5 staged artifacts in expected paths', async () => {
  const dir = await tmpDir();
  const dreamDir = path.join(dir, 'archive', 'dreams', '2026-05-10');
  await fs.mkdir(dreamDir, { recursive: true });
  const { plan } = await runRebuildIndexes({
    memoryRoot: dir, today: '2026-05-10',
    ...EMPTY_SUMMARIES, ...EMPTY_PLANS,
  });
  const { stagedFiles } = await stageRebuildPlan({ plan, dreamDir, today: '2026-05-10' });
  assert.equal(stagedFiles.length, 5);

  // 3 sweep-targeted .tmp files
  const tmpPaths = stagedFiles.filter(p => p.endsWith('.tmp'));
  assert.equal(tmpPaths.length, 3);
  assert.ok(tmpPaths.some(p => p.endsWith('staged/memory-index.md.tmp')));
  assert.ok(tmpPaths.some(p => p.endsWith('staged/pre-action.md.tmp')));
  assert.ok(tmpPaths.some(p => p.endsWith('staged/.dream-log.md.tmp')));

  // 2 archive-only files (live in archive/dreams/<date>/)
  assert.ok(stagedFiles.some(p => p.endsWith('dream-log-entry.md')));
  assert.ok(stagedFiles.some(p => p.endsWith('event.json')));

  // event.json round-trips as valid JSON
  const eventPath = stagedFiles.find(p => p.endsWith('event.json'));
  const ev = JSON.parse(await fs.readFile(eventPath, 'utf8'));
  assert.equal(ev.schema_version, '1.0.0');
});

test('stageRebuildPlan: throws on missing required args', async () => {
  await assert.rejects(() => stageRebuildPlan({}), /plan required/);
});
